BaseScanner: fix _checkout_branch
Avoid the following error on checkout:

    git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
    cmdline: git checkout remotes/origin/14.0
    stderr: 'error: The following untracked working tree files would be overwritten by checkout:
            [...]
    Please move or remove them before you switch branches.
    Aborting'

Could be because to ~/.gitignore config and actual files committed in
different branches?